### PR TITLE
Fix get-webpack-version.js

### LINKED ISSUE #351: Webstorm code assistance broken
**Do you want to request a feature, report a bug or ask a question?**
A bug

**What is the current behavior?**
Webstorm code assistance can't analyse webpack.config.js after including `require('svg-sprite-loader/plugin')`; 

**Steps to reproduce:**
- Setup webstorm with webpack integration (see [instructions](https://www.jetbrains.com/help/webstorm/using-webpack.html))
- require svg-sprite-loader/plugin in your webpack.config.js
- you've got an error:
```
Can't analyse webpack.config.js: coding assistance will ignore module resolution rules in this file.
Possible reasons: this file is not a valid webpack configuration file or its format is not currently supported by the IDE.
Error details:  Cannot read property 'require' of undefined
```
Tested in Webstorm 2018.2 and 2019.2.

**Possible solution:**
```javascript
const webpackVersion = require('webpack/package.json').version;
```
in `lib/utils/get-webpack-version.js`

**Please tell us about your environment:**

- Node.js version: 10.2.1
- webpack version: 3.12.0
- svg-sprite-loader version: 4.1.6
- OS type & version: Ubuntu 16

### PR DESCRIPTION
**Pull request by unkernet**
Fixes #351

### CODE REVIEW

**Comment by abderrahmane-tj** [comment]
@unkernet there is another occurrence of it here https://github.com/kisenka/svg-sprite-loader/blob/master/lib/utils/is-webpack-1.js#L2

**Comment by BeeeQueue** [comment]
Would love to see this merged

**Comment by unkernet** [comment]
> @unkernet there is another occurrence of it here https://github.com/kisenka/svg-sprite-loader/blob/master/lib/utils/is-webpack-1.js#L2

There is no problem here

**Comment by MasaDjordjevic** [comment]
> > @unkernet there is another occurrence of it here https://github.com/kisenka/svg-sprite-loader/blob/master/lib/utils/is-webpack-1.js#L2
> 
> There is no problem here

I'm using VS Code but I'm having the same issue. I think that this line is causing issues because adding a `webpack/package.json` file with `version` property solves the issue.

**Comment by gruzzilkin** [comment]
@abderrahmane-tj, tell me, please, what stops us in this PR?

**Comment by abderrahmane-tj** [comment]
> @abderrahmane-tj, tell me, please, what stops us in this PR?

definitely not me! I don't own this repository, and I need this PR merged as well!

**Comment by ogonkov** [comment]
It's a funny, that this repo is now transferred to JetBrains account, but issue is still exist

**Comment by gruzzilkin** [comment]
Okay, I've found [an issue](https://youtrack.jetbrains.com/issue/WEB-38978) in YouTrack with same problem as #351 and [tweet](https://twitter.com/GruZZ/status/1202845435620143105) about this issue.

**Comment by FrankFang** [comment]
Why not merge this?

**Comment by ogonkov** [comment]
Looks like they want to fix it on IDE side

**Comment by abderrahmane-tj** [comment]
🎉

**Pull request merged**
