### PR TITLE
Update dependency

### PR DESCRIPTION
**Pull request by mayako21126**
**What kind of change does this PR introduce? (bugfix, feature, docs update, improvement)**
improvement
**What is the current behavior? (You can also link to an open issue here)**
https://github.com/JetBrains/svg-sprite-loader/pull/403#issuecomment-740181543
Remove Duplicate Dependencies and Update dependency version(in env folder)
**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**
no
**Please check if the PR fulfills [contributing guidelines](https://github.com/JetBrains/svg-sprite-loader/blob/master/CONTRIBUTING.md#develop)**

### CODE REVIEW

**Comment by ogonkov** [comment]
So it was not required by plugin at all?

**Comment by mayako21126** [comment]
> So it was not required by plugin at all?

image

some dependency in here

**Comment by shakhbulatgaz** [comment]
Any progress on this?

**Comment by d3x42** [comment]
It's merged already

**Pull request merged**
