### PR TITLE
Add webpack 5 support

### PR DESCRIPTION
**Pull request by orlov-vo**
**What kind of change does this PR introduce? (bugfix, feature, docs update, improvement)**
feature

**What is the current behavior? (You can also link to an open issue here)**
Now it doesn't work with Webpack 5

**What is the new behavior (if this is a feature change)?**
It should work with Webpack 5

**Does this PR introduce a breaking change?**
no

**Please check if the PR fulfills [contributing guidelines](https://github.com/kisenka/svg-sprite-loader/blob/master/CONTRIBUTING.md#develop)**
ok

It's is related with #359

### CODE REVIEW

**Comment by orlov-vo** [comment]
It seems like [`webpack-toolkit`](https://github.com/kisenka/webpack-toolkit) isn't compatible with webpack 5

```
$ yarn test:webpack-5
...
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'webpack/lib//MultiEntryPlugin'
Require stack:
- E:\projects\svg-sprite-loader\node_modules\webpack-toolkit\lib\addEntry.js
- E:\projects\svg-sprite-loader\node_modules\webpack-toolkit\index.js
- E:\projects\svg-sprite-loader\test\utils\create-compiler.js
- E:\projects\svg-sprite-loader\test\utils\index.js
- E:\projects\svg-sprite-loader\test\loader.test.js
- E:\projects\svg-sprite-loader\node_modules\mocha\lib\mocha.js
- E:\projects\svg-sprite-loader\node_modules\mocha\index.js
- E:\projects\svg-sprite-loader\node_modules\mocha\bin\_mocha
```

**Comment by sghoweri** [comment]
Any updates on this? Is Webpack v5 support planned / expected?

**Comment by zhongzhong0505** [comment]
svg-sprite-loader

**Comment by netconomy-stephan-dum** [comment]
please close this PR to avoid confusion as its already solved by:
https://github.com/JetBrains/svg-sprite-loader/pull/403

**Pull request closed without merging**
